name: DeityCreative
version: 2.1.0
authors: [ImDeity, KILL3RTACO]
website: http://imdeity.com
description: ImDeity Creative
main: com.imdeity.deitycreative.DeityCreative
depend: [DeityAPI]
commands:
  creative:
    description: ImDeity Creative Commands
    usage: /creative [subcommand]
